<a href="https://colab.research.google.com/github/gautam1218/Data-Science/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

products = []
prices = []

n = int(input("Enter number of products: "))

for i in range(n):
    product = input(f"Enter name of product {i+1}: ")
    price = float(input(f"Enter price of {product}: "))

    products.append(product)
    prices.append(price)

p = np.array(prices)

print("\nProducts and Prices:")
for i in range(n):
    print(products[i], ":", prices[i])

print("\nHighest Price:", p.max())
print("Lowest Price:", p.min())
print("Total Price:", p.sum())
print("Average Price:", p.mean())
print("Standard Deviation:", p.std())

Enter number of products: 5
Enter name of product 1: chiups
Enter price of chiups: 10
Enter name of product 2: bhujia
Enter price of bhujia: 50
Enter name of product 3: kurkure
Enter price of kurkure: 20
Enter name of product 4: namkeen
Enter price of namkeen: 100
Enter name of product 5: nut cracker
Enter price of nut cracker: 200

Products and Prices:
chiups : 10.0
bhujia : 50.0
kurkure : 20.0
namkeen : 100.0
nut cracker : 200.0

Highest Price: 200.0
Lowest Price: 10.0
Total Price: 380.0
Average Price: 76.0
Standard Deviation: 69.45502141674135


In [ ]:
import numpy as np
#create a mat 5*5 matrix of random integer(1-90);
mt = np.random.randint(1,90,(5,5));
print(mt)
print("\n")


#find mean of values col and row wise
row_mean = np.mean(mt, axis=1)
print("Row Means:", row_mean)
print("\n")

col_mean = np.mean(mt, axis=0)
print("Column Means:", col_mean)
print("\n")

#replace all even numbers with -1
even_num = np.where(mt % 2 == 0, -1,mt)
print("Modified Matrix:")
print(even_num)
print("\n")

# sort the mat col and row wise w
srt = np.sort(mt, axis=0)
print("Sorted Matrix col wise :")
print(srt)
print("\n")

srt = np.sort(mt, axis=1)
print("Sorted Matrix row wise :")
print(srt)
print("\n")

# find sum of row and col wise seperately
row_sum = np.sum(mt, axis=1)
print("Row Sums:", row_sum)
print("\n")

col_sum = np.sum(mt, axis=0)
print("Column Sums:", col_sum)
print("\n")

#cnt the number of -ve in each column

cnt_negative = np.sum(np.where(even_num < 0, 1, 0), axis=0)
print("Count of Negative Numbers:", cnt_negative)
print("\n")


[[64  9 24 60 68]
 [11  7 34 65 39]
 [74 11 40 21  8]
 [65 26 56 80 44]
 [ 4  5 78 41 70]]


Row Means: [45.  31.2 30.8 54.2 39.6]


Column Means: [43.6 11.6 46.4 53.4 45.8]


Modified Matrix:
[[-1  9 -1 -1 -1]
 [11  7 -1 65 39]
 [-1 11 -1 21 -1]
 [65 -1 -1 -1 -1]
 [-1  5 -1 41 -1]]


Sorted Matrix col wise :
[[ 4  5 24 21  8]
 [11  7 34 41 39]
 [64  9 40 60 44]
 [65 11 56 65 68]
 [74 26 78 80 70]]


Sorted Matrix row wise :
[[ 9 24 60 64 68]
 [ 7 11 34 39 65]
 [ 8 11 21 40 74]
 [26 44 56 65 80]
 [ 4  5 41 70 78]]


Row Sums: [225 156 154 271 198]


Column Sums: [218  58 232 267 229]


Count of Negative Numbers: [3 1 5 2 4]




In [ ]:
import numpy as np
stock = np.random.randint(1,100,(5,5))
demand= np.random.randint(1,100,(5,5))
# print(stock)
# print("\n")
# print(demand)
# print("\n")

rem_stock = stock - demand
print(rem_stock)
print("\n")

rep_neg_val = np.where(rem_stock < 0, 0,rem_stock)
print(rep_neg_val)
print("\n")

#find
# total shortage
total_shortage = np.sum(np.where(rem_stock < 0, -rem_stock, 0))
print("Total Shortage:", total_shortage)
print("\n")

#products with zero stock
zero_stock_products = np.sum(rep_neg_val == 0, axis=1)
print("Products with Zero Stock:", zero_stock_products)
print("\n")

#sort each row based on remaining stock
sorted_stock = np.sort(rep_neg_val, axis=1)
print("Sorted Stock:")
print(sorted_stock)
print("\n")

[[ 40 -35 -35  37 -22]
 [ -3 -32  24   4  73]
 [-11  -5   3 -56 -20]
 [-23 -32  26  76  -5]
 [ -8  43  31  33 -85]]


[[40  0  0 37  0]
 [ 0  0 24  4 73]
 [ 0  0  3  0  0]
 [ 0  0 26 76  0]
 [ 0 43 31 33  0]]


Total Shortage: 372


Products with Zero Stock: [3 2 4 3 2]


Sorted Stock:
[[ 0  0  0 37 40]
 [ 0  0  4 24 73]
 [ 0  0  0  0  3]
 [ 0  0  0 26 76]
 [ 0  0 31 33 43]]




In [ ]:
import pandas as pd

file_ = pd.read_csv('./student_data.csv',sep=',')
print(file_)
print("\n")
# df = pd.DataFrame(file_)
# print("\n")
# print(df)

# f=df.head(10)
# print("\n")
# print(f)

print(file_.head())
print("\n")
print(file_.tail())

      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7   
1               4          69            5               3   
2              11          60            7               6   
3               8          99            9               8   
4               5          52            8               6   
...           ...         ...          ...             ...   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
0                        10              62      100.00           Placed  
1                         8              56      100.00           Placed  
2                        10   